<a href="https://colab.research.google.com/github/sandy100061/MachineLearningAssignment/blob/main/Assignment3/Code/Question%20d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as npy;
# 1.d new shape to an array without changing its data. Reshape 3x2:
oneD = npy.arange(1, 7)
print ("1.d Array: ", oneD)
# reshape to 3x2
oneD = oneD.reshape(3, 2)
print ("1.d Reshaped array 3x2: \n", oneD)
# reshape to 2x3
oneD = oneD.reshape(2, 3)
print ("1.d Reshaped array 2x3: \n", oneD)

1.d Array:  [1 2 3 4 5 6]
1.d Reshaped array 3x2: 
 [[1 2]
 [3 4]
 [5 6]]
1.d Reshaped array 2x3: 
 [[1 2 3]
 [4 5 6]]
