<a href="https://colab.research.google.com/github/sandy100061/MachineLearningAssignment/blob/main/Assignment3/Code/Question%20a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import numpy as npy;

# 1.a
vector = npy.random.randint(1, 20, 15)
print ("1.a Vector: ", vector)
# 1.a.1 Reshape the array to 3 by 5
reshaped = vector.reshape(3, 5)
print("Array after reshaped :", reshaped)
print ("1.a.2 Reshaped array shape: ", reshaped.shape)

# 1.a.3 Replace the max in each row by 0.
for i in range(reshaped.shape[0]):
    reshaped[i, npy.where(reshaped[i] == reshaped[i].max())] = 0
print ("1.a.3 Replaced max in each row by 0: \n", reshaped)

# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array = npy.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]], dtype=npy.int32)

# Print the array
print("Array:")
print(array)

# Print the shape of the array
print("\nShape:", array.shape)

# Print the type of the array
print("\nType:", type(array))

# Print the data type of the array
print("\nData Type:", array.dtype)

1.a Vector:  [ 2 17  1 16 10 15  2  9  6 11  7  7 13  2 16]
Array after reshaped : [[ 2 17  1 16 10]
 [15  2  9  6 11]
 [ 7  7 13  2 16]]
1.a.2 Reshaped array shape:  (3, 5)
1.a.3 Replaced max in each row by 0: 
 [[ 2  0  1 16 10]
 [ 0  2  9  6 11]
 [ 7  7 13  2  0]]
Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape: (4, 3)

Type: <class 'numpy.ndarray'>

Data Type: int32
